name: Rugby Prediction Workflow
on:
  schedule:
    - cron: '0 18 * * 4'  # Thursday 6 PM
    - cron: '0 18 * * 5'  # Friday 6 PM
  workflow_dispatch:

jobs:
  run-predictions:
    runs-on: ubuntu-latest
    env:
      TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        
    - name: Run Predictions
      run: python src/main.py
      
    - name: Send to Telegram
      if: ${{ always() }}
      run: |
        # Logic to send results
