name: Daily Data Pipeline
on:
  schedule:
    - cron: '0 3 * * *'  # Run at 3 AM UTC every day
  workflow_dispatch:     # Allow manual triggering

jobs:
  run-pipeline:
    runs-on: ubuntu-latest
    env:
      SPORTSDAR_API_KEY: ${{ secrets.SPORTSDAR_API_KEY }}
      WEATHER_API_KEY: ${{ secrets.WEATHER_API_KEY }}
      PYTHONPATH: ${{ github.workspace }}/src
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Create data directories
      run: |
        mkdir -p data/raw/fixtures
        mkdir -p data/raw/teams
        mkdir -p data/raw/players
        mkdir -p data/raw/weather
        mkdir -p data/raw/injuries
        mkdir -p data/raw/transfers
        mkdir -p data/processed/features
        mkdir -p logs
        
    - name: Run Daily Data Pipeline
      run: python -m src.data_collection.update_daily
      
    - name: Archive processed data
      uses: actions/upload-artifact@v3
      with:
        name: processed-data-${{ github.run_id }}
        path: |
          data/processed/
          logs/
        retention-days: 3
        
    - name: Commit and push updated data
      if: ${{ success() }}
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add data/processed/
        git commit -m "Auto-update: Processed data ${{ github.run_id }}" || echo "No changes to commit"
        git push origin HEAD:${{ github.ref }} || echo "No changes to push"
        
    - name: Send success notification
      if: ${{ success() }}
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_COLOR: good
        SLACK_TITLE: "Data Pipeline Success"
        SLACK_MESSAGE: "Daily rugby data pipeline completed successfully\nRun: ${{ github.run_id }}"
        
    - name: Send failure notification
      if: ${{ failure() }}
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_COLOR: danger
        SLACK_TITLE: "Data Pipeline Failed"
        SLACK_MESSAGE: "Daily rugby data pipeline failed\nRun: ${{ github.run_id }}\nJob: ${{ github.job }}"
